# Generated by Django 5.2.7 on 2025-11-02 19:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="Слаг"
                    ),
                ),
                (
                    "vin",
                    models.CharField(blank=True, max_length=32, verbose_name="VIN"),
                ),
                ("brand", models.CharField(max_length=80, verbose_name="Марка")),
                ("model_name", models.CharField(max_length=80, verbose_name="Модель")),
                (
                    "generation",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Поколение"
                    ),
                ),
                (
                    "manufacture_year",
                    models.PositiveSmallIntegerField(verbose_name="Год выпуска"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="BYN", max_length=3, verbose_name="Валюта"
                    ),
                ),
                (
                    "mileage_km",
                    models.PositiveIntegerField(default=0, verbose_name="Пробег (км)"),
                ),
                (
                    "body_type",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Тип кузова"
                    ),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=80, verbose_name="Цвет"),
                ),
                (
                    "transmission",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Трансмиссия"
                    ),
                ),
                (
                    "drive_type",
                    models.CharField(blank=True, max_length=80, verbose_name="Привод"),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Тип топлива"
                    ),
                ),
                (
                    "engine_capacity_l",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="Объем двигателя (л)",
                    ),
                ),
                (
                    "engine_power_hp",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Мощность (л.с.)"
                    ),
                ),
                (
                    "owners_count",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Количество владельцев"
                    ),
                ),
                (
                    "customs_cleared",
                    models.BooleanField(default=True, verbose_name="Растаможен"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "contact_name",
                    models.CharField(max_length=120, verbose_name="Контактное лицо"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=30, verbose_name="Телефон"),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("review", "На модерации"),
                            ("ready", "Готово к публикации"),
                            ("published", "Опубликовано"),
                            ("archived", "Архив"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Изменено",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата публикации"
                    ),
                ),
            ],
            options={
                "verbose_name": "Автомобиль",
                "verbose_name_plural": "Автомобили",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="Слаг"),
                ),
            ],
            options={
                "verbose_name": "Особенность",
                "verbose_name_plural": "Особенности",
                "ordering": ["category__title", "title"],
            },
        ),
        migrations.CreateModel(
            name="FeatureCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Слаг"),
                ),
            ],
            options={
                "verbose_name": "Категория особенностей",
                "verbose_name_plural": "Категории особенностей",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="PublicationChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Код")),
                ("title", models.CharField(max_length=120, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("active", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "integration_notes",
                    models.TextField(
                        blank=True,
                        help_text="Ссылки на API, требования к данным, контакт модераторов",
                        verbose_name="Комментарии по интеграции",
                    ),
                ),
            ],
            options={
                "verbose_name": "Канал публикации",
                "verbose_name_plural": "Каналы публикации",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="CarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to="cars/%Y/%m/%d", verbose_name="Изображение"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Подпись"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Основное фото"),
                ),
                (
                    "ordering",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="inventory.car",
                        verbose_name="Автомобиль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото автомобиля",
                "verbose_name_plural": "Фотографии автомобилей",
                "ordering": ["ordering", "id"],
            },
        ),
        migrations.AddField(
            model_name="car",
            name="features",
            field=models.ManyToManyField(
                blank=True,
                related_name="cars",
                to="inventory.feature",
                verbose_name="Особенности",
            ),
        ),
        migrations.AddField(
            model_name="feature",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="features",
                to="inventory.featurecategory",
                verbose_name="Категория",
            ),
        ),
        migrations.CreateModel(
            name="PublicationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Идентификатор на площадке",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Успех"),
                            ("failed", "Ошибка"),
                            ("pending", "В обработке"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="Ошибка")),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата публикации на площадке",
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publication_logs",
                        to="inventory.car",
                        verbose_name="Автомобиль",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_logs",
                        to="inventory.publicationchannel",
                        verbose_name="Канал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог публикации",
                "verbose_name_plural": "Логи публикаций",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(fields=["status"], name="inventory_c_status_ad60d3_idx"),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(
                fields=["brand", "model_name"], name="inventory_c_brand_02c33b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publicationlog",
            index=models.Index(
                fields=["channel", "status"], name="inventory_p_channel_6ff532_idx"
            ),
        ),
    ]
