# Generated by Django 5.2.7 on 2025-11-02 21:45

from django.db import migrations, models


def forwards_populate_make_model(apps, schema_editor):
    Make = apps.get_model("inventory", "Make")
    CarModel = apps.get_model("inventory", "CarModel")
    Car = apps.get_model("inventory", "Car")
    from django.utils.text import slugify

    def unique_slug(model, base_slug, **filters):
        slug = base_slug or "item"
        candidate = slug
        index = 1
        lookup = {"slug": candidate, **filters}
        while model.objects.filter(**lookup).exists():
            index += 1
            candidate = f"{slug}-{index}"
            lookup["slug"] = candidate
        return candidate

    for car in Car.objects.all():
        brand = getattr(car, "brand", "") or "Unknown"
        model_title = getattr(car, "model_name", "") or "Unknown"
        make_slug = unique_slug(Make, slugify(brand) or "make")
        make, _ = Make.objects.get_or_create(
            title=brand,
            defaults={"slug": make_slug},
        )
        model_slug = unique_slug(
            CarModel,
            slugify(model_title) or "model",
            make=make,
        )
        car_model, _ = CarModel.objects.get_or_create(
            make=make,
            title=model_title,
            defaults={"slug": model_slug},
        )
        car.make = make
        car.model = car_model
        car.save(update_fields=["make", "model"])


def reverse_populate_make_model(apps, schema_editor):
    Car = apps.get_model("inventory", "Car")
    for car in Car.objects.select_related("make", "model"):
        car.brand = car.make.title
        car.model_name = car.model.title
        car.save(update_fields=["brand", "model_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Make",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=80, unique=True, verbose_name="Марка")),
                ("slug", models.SlugField(max_length=80, unique=True, verbose_name="Слаг")),
            ],
            options={
                "verbose_name": "Марка",
                "verbose_name_plural": "Марки",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="CarModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=80, verbose_name="Модель")),
                ("slug", models.SlugField(max_length=120, verbose_name="Слаг")),
                (
                    "make",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="models",
                        to="inventory.make",
                        verbose_name="Марка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Модель",
                "verbose_name_plural": "Модели",
                "ordering": ["make__title", "title"],
            },
        ),
        migrations.AddConstraint(
            model_name="carmodel",
            constraint=models.UniqueConstraint(
                fields=("make", "title"), name="unique_model_per_make"
            ),
        ),
        migrations.AddConstraint(
            model_name="carmodel",
            constraint=models.UniqueConstraint(
                fields=("make", "slug"), name="unique_model_slug_per_make"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="make",
            field=models.ForeignKey(
                null=True,
                on_delete=models.deletion.PROTECT,
                related_name="cars",
                to="inventory.make",
                verbose_name="Марка",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="model",
            field=models.ForeignKey(
                null=True,
                on_delete=models.deletion.PROTECT,
                related_name="cars",
                to="inventory.carmodel",
                verbose_name="Модель",
            ),
        ),
        migrations.RunPython(forwards_populate_make_model, reverse_populate_make_model),
        migrations.AlterField(
            model_name="car",
            name="make",
            field=models.ForeignKey(
                on_delete=models.deletion.PROTECT,
                related_name="cars",
                to="inventory.make",
                verbose_name="Марка",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="model",
            field=models.ForeignKey(
                on_delete=models.deletion.PROTECT,
                related_name="cars",
                to="inventory.carmodel",
                verbose_name="Модель",
            ),
        ),
        migrations.RemoveIndex(
            model_name="car",
            name="inventory_c_brand_02c33b_idx",
        ),
        migrations.RemoveField(
            model_name="car",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="car",
            name="model_name",
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(
                fields=["make", "model"], name="inventory_c_make_id_2376fa_idx"
            ),
        ),
    ]
